version: "3"

services:
  tfserving:
    build: tfserving/
    ports: 
      - 8500:8500
      - 8501:8501
    networks:
      - deploy_network
    container_name: tfserving

  streamlit:
    build: streamlit/
    depends_on:
      - tfserving
    ports: 
        - 8502:8502
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge