version: "3"

services:
  tfserving:
    build: src/tfserving/
    ports: 
      - 8500:8500
      - 8501:8501
    networks:
      - backend
    container_name: tfserving

  streamlit:
    build: src/streamlit/
    depends_on:
      - tfserving
    ports: 
        - 8502:8502
    networks:
      - backend
    container_name: streamlit

networks:
  backend:
    driver: bridge